version: "3.7"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - api-postgres

  api:
    image: node:lts-alpine
    build: .
    volumes:
      - ./:/home/api
      - /home/api/node_modules
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - api-postgres

volumes:
  pgdata:

networks:
  api-postgres:
    driver: bridge
